<?xml version="1.0"?>
<package format="3">
  <name>pcd_fpfh</name>
  <version>0.0.0</version>
  <description>Compute FPFH descriptors and publish detections</description>
  <maintainer email="itzkamalkant@gmail.com">rm</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <!-- Build dependencies -->
  <build_depend>rclcpp</build_depend>
  <build_depend>sensor_msgs</build_depend>
  <build_depend>pcl_conversions</build_depend>
  <build_depend>pcc</build_depend>
  <build_depend>custom_interfaces</build_depend>
  <build_depend>visualization_msgs</build_depend>

  <!-- Execution dependencies -->
  <exec_depend>rclcpp</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>pcl_conversions</exec_depend>
  <exec_depend>pcc</exec_depend>
  <exec_depend>custom_interfaces</exec_depend>
  <exec_depend>visualization_msgs</exec_depend>

  <!-- Test dependencies -->
  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
